css:
  enabled: true
  src:
    - scss/**/*.scss
    - "!scss/colorizer.scss"
  dest: assets/css/
  lint: false
  # enables additional debugging information in the output file as CSS comments - only use when necessary
  sourceComments: false
  sourceMapEmbed: false
   # tell the compiler whether you want 'expanded' or 'compressed'
  outputStyle: expanded
  autoPrefixerBrowsers: # https://github.com/ai/browserslist#queries
    - last 2 versions
    - IE >= 9
  includePaths:
    - bower_components/bootstrap-sass/assets/stylesheets
    - bower_components/font-awesome/scss
    - bower_components/compass-mixins/lib
js:
  enabled: true
  src:
    - js/**/*.js
  dest: assets/js/
  destName: oa_theme.script.min.js
  sourceMapEmbed: false
  babel: true
  eslint:
    enabled: false
    src:
      - js/**/*.js
      - gulpfile.js
fonts:
  enabled: true
  src:
    - bower_components/font-awesome/fonts/**.*"
  dest: assets/fonts/
patternLab:
  enabled: false
  src:
    data: pattern_lab/data/
    patternLabFiles: pattern_lab/patternlab-files/
    patterns: pattern_lab/patterns/
    patternLabCss: pattern_lab/patternlab-css/
  dest: pattern_lab/public/
#  config: config--pattern-lab.json
  injectFiles:
    - bower_components/modernizr/modernizr.js
  injectBower: true
icons: # https://github.com/nfroidure/gulp-iconfont
  enabled: false
  src: images/icons/src/*.svg
  dest: images/icons/output/
  fontPathPrefix: ../images/icons/output/
  classNamePrefix: icon
  autohint: false
  normalize: false
  templates:
    css:
      src: images/icons/templates/_icons.scss
      dest: scss/00-config/
    demo:
      src: images/icons/templates/icons.mustache
      dest: pattern-lab/source/_patterns/00-atoms/04-images/icons.mustache
  formats:
    - ttf
    - eot
    - woff
    - svg
browserSync:
  enabled: false
  port: 3050
  watchFiles:
    # - template.php
  domain: http://local.atrium # enable when full CMS is set up
  baseDir: ./
  #startPath: pattern-lab/public/
  openBrowserAtStart: true
  # requires above to be true; allows non-default browser to open
  browser:
    - Google Chrome
  # Tunnel the Browsersync server through a random Public URL
  # -> http://randomstring23232.localtunnel.me
  tunnel: false
  reloadDelay: 50
  reloadDebounce: 250
drupal:
  enabled: true
  # when these files change
  watch:
    - template.php
    - templates/**
    - includes/**
    - panels/**
  # run this command
  command: drush cc all
  # in this directory
  dir: ../../../../
  inject:
    bower: false
    file: oa_theme.info
    # files to not inject into Drupal theme file
    # ignoreFiles:
    #   - lodash.js
